name: CitDeploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.set_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@main

      - name: Prepare CIT zip
        run: |
          zip -r mkcit.zip assets/ pack.mcmeta
          rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set new tag output
        id: set_tag
        run: echo "new_tag=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_tag }}
          release_name: Release ${{ env.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/mkcit.zip
          asset_name: mkcit.zip
          asset_content_type: application/zip
