name: CitDeploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@main
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
      - name: Prepare CIT zip
        run: |
          zip -r mkcit.zip assets/ pack.mcmeta
          rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
          cd release
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: Spbog
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
      - name: Set new tag output
        run: echo "new_tag=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV
      - name: Debug tag
        run: echo "New tag is ${{ steps.tag_version.outputs.new_tag }}"
      - name: List files in release directory
        run: ls -la ./release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@main
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.new_tag }}
          release_name: Release ${{ needs.build.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/mkcit.zip
          asset_name: mkcit.zip
          asset_content_type: application/zip
